//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int idCliente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int dni { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public int caracteristica { get; set; }
        public int telefono { get; set; }
        public string email { get; set; }
        public string calle { get; set; }
        public Nullable<int> altura { get; set; }
        public string estado { get; set; }
    }
}
