//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int idProducto { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public string estado { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idCategoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
